# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 556)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setToolTipDuration(1)
        self.centralwidget.setStyleSheet("QWidget {\n"
"            background-color: #353535;\n"
"            color: #ffffff;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #353535;\n"
"    color: white;\n"
"    margin: 2px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 5px 30px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    border: 1px solid black;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: black;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"    border-radius: 8px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu.sizePolicy().hasHeightForWidth())
        self.side_menu.setSizePolicy(sizePolicy)
        self.side_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.side_menu.setStyleSheet("background: rgb(42, 42, 42)")
        self.side_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.side_menu)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.open_folder_button = QtWidgets.QPushButton(self.frame)
        self.open_folder_button.setWhatsThis("")
        self.open_folder_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.open_folder_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_folder_button.setIcon(icon)
        self.open_folder_button.setObjectName("open_folder_button")
        self.verticalLayout_7.addWidget(self.open_folder_button)
        self.open_file_button = QtWidgets.QPushButton(self.frame)
        self.open_file_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"")
        self.open_file_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file_button.setIcon(icon1)
        self.open_file_button.setIconSize(QtCore.QSize(16, 16))
        self.open_file_button.setObjectName("open_file_button")
        self.verticalLayout_7.addWidget(self.open_file_button)
        self.save_playlist_button = QtWidgets.QPushButton(self.frame)
        self.save_playlist_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"")
        self.save_playlist_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_playlist_button.setIcon(icon2)
        self.save_playlist_button.setObjectName("save_playlist_button")
        self.verticalLayout_7.addWidget(self.save_playlist_button)
        self.open_playlist_button = QtWidgets.QPushButton(self.frame)
        self.open_playlist_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"")
        self.open_playlist_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/folder-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_playlist_button.setIcon(icon3)
        self.open_playlist_button.setObjectName("open_playlist_button")
        self.verticalLayout_7.addWidget(self.open_playlist_button)
        self.delete_playlist = QtWidgets.QPushButton(self.frame)
        self.delete_playlist.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"")
        self.delete_playlist.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/folder-minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_playlist.setIcon(icon4)
        self.delete_playlist.setObjectName("delete_playlist")
        self.verticalLayout_7.addWidget(self.delete_playlist)
        self.verticalLayout_6.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.side_menu)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.change_theme_button = QtWidgets.QPushButton(self.frame_2)
        self.change_theme_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.change_theme_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53)\n"
"}")
        self.change_theme_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/feather.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_theme_button.setIcon(icon5)
        self.change_theme_button.setObjectName("change_theme_button")
        self.verticalLayout_8.addWidget(self.change_theme_button)
        self.verticalLayout_6.addWidget(self.frame_2, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("QFrame {\n"
"    background: #353535; \n"
"}")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setStyleSheet("background: #353535;")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.header)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.header)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.search_line_edit = QtWidgets.QLineEdit(self.frame_12)
        self.search_line_edit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(74, 74, 74);\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    color: white;\n"
"    border-bottom:1px solid rgb(85, 255, 127);\n"
"}")
        self.search_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.search_line_edit.setClearButtonEnabled(True)
        self.search_line_edit.setObjectName("search_line_edit")
        self.verticalLayout_4.addWidget(self.search_line_edit)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.body_content = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body_content.sizePolicy().hasHeightForWidth())
        self.body_content.setSizePolicy(sizePolicy)
        self.body_content.setStyleSheet("")
        self.body_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_content.setObjectName("body_content")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.body_content)
        self.verticalLayout_5.setContentsMargins(5, 0, 2, 2)
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.body_content)
        font = QtGui.QFont()
        font.setFamily("MS Outlook")
        font.setPointSize(8)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background:#393939;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(74, 74, 74);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(74, 74, 74);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(74, 74, 74);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #393939;\n"
"    height: 14px; /* Set the width instead of the height */\n"
"    margin: 0 15px 0 15px; /* Adjust the margins accordingly */\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/* HANDLE BAR HORIZONTAL */\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(74, 74, 74);\n"
"    min-width: 30px; /* Set the height instead of the width */\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"/* BTN LEFT - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"       background-color: rgb(74, 74, 74);\n"
"    width: 15px; /* Set the height instead of the width */\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left; /* Change subcontrol position to left */\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"/* BTN RIGHT - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(74, 74, 74);\n"
"    width: 15px; /* Set the height instead of the width */\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right; /* Change subcontrol position to right */\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::left-arrow:horizontal,\n"
"QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.playlist_widget = QtWidgets.QListWidget()
        self.playlist_widget.setGeometry(QtCore.QRect(0, 0, 712, 414))
        font = QtGui.QFont()
        font.setFamily("Victoria")
        font.setPointSize(10)
        self.playlist_widget.setFont(font)
        self.playlist_widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playlist_widget.setAutoFillBackground(True)
        self.playlist_widget.setStyleSheet("QListWidget {\n"
"    background-color: #353535;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    background-color: #353535;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    letter-spacing: 3px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    color: rgb(85, 255, 127);\n"
"}")
        self.playlist_widget.setDragEnabled(False)
        self.playlist_widget.setDragDropOverwriteMode(False)
        self.playlist_widget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.playlist_widget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.playlist_widget.setAlternatingRowColors(False)
        self.playlist_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.playlist_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.playlist_widget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.playlist_widget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.playlist_widget.setObjectName("playlist_widget")
        self.playlist_widget.setSpacing(5)
        self.scrollArea.setWidget(self.playlist_widget)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.body_content)
        self.footer = QtWidgets.QFrame(self.main_body)
        self.footer.setStyleSheet("background: #353535;\n"
"")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.footer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.footer)
        self.frame_7.setStyleSheet("background: rgb(53,53,53)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.song_label = QtWidgets.QLabel(self.frame_7)
        self.song_label.setStyleSheet("color: white;\n"
"font-weight:bold;")
        self.song_label.setText("")
        self.song_label.setObjectName("song_label")
        self.horizontalLayout_6.addWidget(self.song_label)
        self.verticalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.frame_5 = QtWidgets.QFrame(self.footer)
        self.frame_5.setStyleSheet("background: #353535;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.duration_label = QtWidgets.QLabel(self.frame_5)
        self.duration_label.setStyleSheet("color: white;\n"
"font-weight: bold;")
        self.duration_label.setObjectName("duration_label")
        self.horizontalLayout_5.addWidget(self.duration_label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.duration_slider = QtWidgets.QSlider(self.frame_5)
        self.duration_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: grey;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color:rgb(85, 255, 127);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 255, 0);\n"
"    border: none;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin: -3px 0;\n"
"    border-radius: 5px;\n"
"}")
        self.duration_slider.setOrientation(QtCore.Qt.Horizontal)
        self.duration_slider.setObjectName("duration_slider")
        self.horizontalLayout_5.addWidget(self.duration_slider, 0, QtCore.Qt.AlignVCenter)
        self.duration_label_2 = QtWidgets.QLabel(self.frame_5)
        self.duration_label_2.setStyleSheet("color: white;\n"
"font-weight: bold;")
        self.duration_label_2.setObjectName("duration_label_2")
        self.horizontalLayout_5.addWidget(self.duration_label_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignVCenter)
        self.frame_6 = QtWidgets.QFrame(self.footer)
        self.frame_6.setStyleSheet("background: #353535;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.language_button = QtWidgets.QPushButton(self.frame_10)
        self.language_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.language_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/globe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.language_button.setIcon(icon6)
        self.language_button.setIconSize(QtCore.QSize(20, 20))
        self.language_button.setObjectName("language_button")
        self.horizontalLayout_4.addWidget(self.language_button)
        self.sound_button = QtWidgets.QPushButton(self.frame_10)
        self.sound_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.sound_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/volume-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_button.setIcon(icon7)
        self.sound_button.setIconSize(QtCore.QSize(20, 20))
        self.sound_button.setObjectName("sound_button")
        self.horizontalLayout_4.addWidget(self.sound_button)
        self.volume_slider = QtWidgets.QSlider(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_slider.sizePolicy().hasHeightForWidth())
        self.volume_slider.setSizePolicy(sizePolicy)
        self.volume_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: grey;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color:rgb(85, 255, 127);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 255, 0);\n"
"    border: none;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin: -3px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider {\n"
"    border-radius: 2px;\n"
"}")
        self.volume_slider.setProperty("value", 99)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_4.addWidget(self.volume_slider)
        self.horizontalLayout_2.addWidget(self.frame_10, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previous_button = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_button.sizePolicy().hasHeightForWidth())
        self.previous_button.setSizePolicy(sizePolicy)
        self.previous_button.setMinimumSize(QtCore.QSize(0, 0))
        self.previous_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 4px 8px;\n"
"            border-radius: 12px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.previous_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/skip-back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_button.setIcon(icon8)
        self.previous_button.setIconSize(QtCore.QSize(20, 20))
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_3.addWidget(self.previous_button)
        self.pre_button = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_button.sizePolicy().hasHeightForWidth())
        self.pre_button.setSizePolicy(sizePolicy)
        self.pre_button.setMinimumSize(QtCore.QSize(0, 0))
        self.pre_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 4px 8px;\n"
"            border-radius: 12px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.pre_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/rewind.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pre_button.setIcon(icon9)
        self.pre_button.setIconSize(QtCore.QSize(20, 20))
        self.pre_button.setObjectName("pre_button")
        self.horizontalLayout_3.addWidget(self.pre_button)
        self.play_button = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 4px 8px;\n"
"            border-radius: 12px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.play_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/play-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon10)
        self.play_button.setIconSize(QtCore.QSize(32, 32))
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_3.addWidget(self.play_button)
        self.forw_button = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forw_button.sizePolicy().hasHeightForWidth())
        self.forw_button.setSizePolicy(sizePolicy)
        self.forw_button.setMinimumSize(QtCore.QSize(0, 0))
        self.forw_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 4px 8px;\n"
"            border-radius: 12px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.forw_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/fast-forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forw_button.setIcon(icon11)
        self.forw_button.setIconSize(QtCore.QSize(20, 20))
        self.forw_button.setObjectName("forw_button")
        self.horizontalLayout_3.addWidget(self.forw_button)
        self.following_button = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.following_button.sizePolicy().hasHeightForWidth())
        self.following_button.setSizePolicy(sizePolicy)
        self.following_button.setMinimumSize(QtCore.QSize(0, 0))
        self.following_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 4px 8px;\n"
"            border-radius: 12px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.following_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/skip-forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.following_button.setIcon(icon12)
        self.following_button.setIconSize(QtCore.QSize(20, 20))
        self.following_button.setObjectName("following_button")
        self.horizontalLayout_3.addWidget(self.following_button)
        self.horizontalLayout_2.addWidget(self.frame_9, 0, QtCore.Qt.AlignHCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.shuffle_button = QtWidgets.QPushButton(self.frame_8)
        self.shuffle_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.shuffle_button.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/repeat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffle_button.setIcon(icon13)
        self.shuffle_button.setObjectName("shuffle_button")
        self.gridLayout.addWidget(self.shuffle_button, 0, 4, 1, 1)
        self.sound_menu_button = QtWidgets.QPushButton(self.frame_8)
        self.sound_menu_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.sound_menu_button.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/sliders.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_menu_button.setIcon(icon14)
        self.sound_menu_button.setObjectName("sound_menu_button")
        self.gridLayout.addWidget(self.sound_menu_button, 0, 5, 1, 1)
        self.replay_button = QtWidgets.QPushButton(self.frame_8)
        self.replay_button.setStyleSheet("QToolTip {\n"
"    padding: 3px; \n"
"     background-color: #353535;\n"
"    color: white;\n"
"    font-weight:bold;\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"            color: #ffffff;\n"
"            border: none;\n"
"            padding: 2px 6px;\n"
"            border-radius: 5px;  \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(74, 74, 74);\n"
"}")
        self.replay_button.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.replay_button.setIcon(icon15)
        self.replay_button.setCheckable(True)
        self.replay_button.setObjectName("replay_button")
        self.gridLayout.addWidget(self.replay_button, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_8, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.footer, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_folder_button.setToolTip(_translate("MainWindow", "Open folder"))
        self.open_file_button.setToolTip(_translate("MainWindow", "Open file"))
        self.save_playlist_button.setToolTip(_translate("MainWindow", "Save playlist"))
        self.open_playlist_button.setToolTip(_translate("MainWindow", "Open playlist"))
        self.delete_playlist.setToolTip(_translate("MainWindow", "Delete playlist"))
        self.change_theme_button.setToolTip(_translate("MainWindow", "Change Theme"))
        self.search_line_edit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.duration_label.setText(_translate("MainWindow", "00:00"))
        self.duration_label_2.setText(_translate("MainWindow", "00:00"))
        self.language_button.setToolTip(_translate("MainWindow", "Switch language"))
        self.sound_button.setToolTip(_translate("MainWindow", "Mute"))
        self.previous_button.setToolTip(_translate("MainWindow", "Previous"))
        self.pre_button.setToolTip(_translate("MainWindow", "- 15"))
        self.play_button.setToolTip(_translate("MainWindow", "Play"))
        self.forw_button.setToolTip(_translate("MainWindow", "+ 15 "))
        self.following_button.setToolTip(_translate("MainWindow", "Following"))
        self.shuffle_button.setToolTip(_translate("MainWindow", "Shuffle"))
        self.sound_menu_button.setToolTip(_translate("MainWindow", "Additional parameters"))
        self.replay_button.setToolTip(_translate("MainWindow", "Replay"))
import icons_rc
